services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "(!)Password"
      MSSQL_PID: "developer"
    volumes:
      - /home/so/docker/sqlserver/data:/var/opt/mssql
